<?php
/**
 * Copyright © 2019 Trunkrs. All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block TrunkrsShipping */

use Trunkrs\Carrier\Block\Adminhtml\System\Config\TrunkrsShipping;

echo "<div id='trunkrs-app'></div>";
?>
<script>
    require([
        'react-app',
    ], function () {
        console.log('Trunkrs assets loaded!')
    });
</script>
<script id=<?php echo "__". $block::TRUNKRS_MAGE_SETTINGS ."__"; ?> type="application/json">
    <?php
    echo json_encode([
        'isConfigured' => $block->getIsConfigured(),
        'accessToken' => $block->getAccessToken(),
        'baseUrl' => $block->getBaseUrl(),
        'domainName' => parse_url($block->getBaseUrl())['host'],
        'details' => json_decode($block->getIntegrationDetails() ?? '{}'),
        'magentoToken' => $block->getMagentoToken(),
        'metaBag' => [
            'magentoVersion' => $block->getMagentoVersion(),
            'browserInfo' => $_SERVER['HTTP_USER_AGENT'],
            'phpVersion' => phpversion(),
            'phpExtensions' => get_loaded_extensions(),
            'pluginVersion' => 'v2.3.0'
        ],
        'disableAutoShipment' => $block->getDisableAutoShipment()
    ]);
    ?>
</script>
